Updated CI pipeline to run unittests only when other checks were successful

diff --git a/.github/workflows/formatting_checks.yml b/.github/workflows/formatting_checks.yml
--- a/.github/workflows/formatting_checks.yml
+++ b/.github/workflows/formatting_checks.yml
@@ -71,3 +71,24 @@ jobs:
     - name: Check copyrights
       run: |
         python formatter.py --copyright --check --git-only
+
+  formatting_checks_passed:
+    name: All formatting checks passed
+    runs-on: ubuntu-latest
+    needs:
+      - check_ruff_formatting
+      - check_ruff_linting
+      - check_reuse
+      - check_copyrights
+    if: always()
+    steps:
+      - name: Decide whether the needed jobs succeeded or failed
+        run: |
+          if [[ ${{ needs.check_ruff_formatting.result }} == 'failure' || \
+                ${{ needs.check_ruff_linting.result }} == 'failure' || \
+                ${{ needs.check_reuse.result }} == 'failure' || \
+                ${{ needs.check_copyrights.result }} == 'failure' ]]; then
+            echo "One or more formatting checks failed"
+            exit 1
+          fi
+
diff --git a/.github/workflows/version_check.yml b/.github/workflows/version_check.yml
--- a/.github/workflows/version_check.yml
+++ b/.github/workflows/version_check.yml
@@ -31,3 +31,17 @@ jobs:
       run: |
         python formatter.py --version
 
+  version_checks_passed:
+    name: All version checks passed
+    runs-on: ubuntu-latest
+    needs:
+      - check_version_tags
+    if: always()
+    steps:
+      - name: Decide whether the needed jobs succeeded or failed
+        run: |
+          if [[ ${{ needs.check_version_tags.result }} == 'failure' ]]; then
+            echo "One or more version checks failed"
+            exit 1
+          fi
+
