Overhauled the documentation build check to force a new build after updating pydidas with pip.

diff --git a/.github/workflows/formatting_checks.yml b/.github/workflows/formatting_checks.yml
--- a/.github/workflows/formatting_checks.yml
+++ b/.github/workflows/formatting_checks.yml
@@ -72,3 +72,23 @@ jobs:
       run: |
         python formatter.py --copyright --check --git-only
 
+  check_docs_built_flag:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Check out source repository
+      uses: actions/checkout@v3
+    - name: Verify docs-built.yml content
+      run: |
+        expected_content="docs-built: false\n"
+        file_path="src/pydidas/sphinx/docs-built.yml"
+        if [[ ! -f "$file_path" ]]; then
+          echo "Error: $file_path does not exist."
+          exit 1
+        fi
+        actual_content=$(cat "$file_path")
+        if [[ "$actual_content" != "$expected_content" ]]; then
+          echo "Error: $file_path content is not as expected."
+          echo "Expected: $expected_content"
+          echo "Found: $actual_content"
+          exit 1
+        fi
